countries_mapping = {
    "SN": "SINGAPORE",
    "MY": "MALAYSIA",
    "BX": "BRUNEI",
    "ID": "INDONESIA",
    "RP": "PHILIPPINES",
    "IN": "INDIA",
    "TH": "THAILAND",
    "VM": "VIETNAM",
    "HK": "HONG KONG",
    "CH": "CHINA",
    "BM": "BURMA",
    "CB": "CAMBODIA",
    "LA": "LAOS",
    "TW": "TAIWAN",
    "KN": "NORTH KOREA",
    "KS": "SOUTH KOREA",
    "JA": "JAPAN",
    "TT": "TIMOR LESTE",
    "MC": "MACAU",
    "AS": "AUSTRALIA",
    "AE": "UNITED ARAB EMIRATES"
}
