event_codes_mapping = {"042": "Make a visit", "043": "Host a visit", "044": "Meet at third location", "045": "Mediate",
                       "046": "Engage in negotiation", "057": "Sign formal agreement",
                       "064": "Share intelligence or information", "07": "Provide aid",
                       "070": "Provide unspecified aid", "071": "Provide economic aid", "072": "Provide military aid",
                       "073": "Provide humanitarian aid", "074": "Provide military protection or peacekeeping",
                       "075": "Grant asylum", "08": "Yield", "145": "Protest violently, riot, not specified below",
                       "1451": "Engage in violent protest for leadership change",
                       "1452": "Engage in violent protest for policy change",
                       "1453": "Engage in violent protest for rights",
                       "1454": "Engage in violent protest for change in institutions, regime",
                       "15": "EXHIBIT FORCE POSTURE",
                       "150": "Demonstrate military or police power, not specified below",
                       "080": "Yield, not specified below", "081": "Ease administrative sanctions, not specified below",
                       "0811": "Ease restrictions on political freedoms", "151": "Increase police alert status",
                       "152": "Increase military alert status", "153": "Mobilize or increase police power",
                       "154": "Mobilize or increase armed forces", "155": "Mobilize or increase cyber-forces",
                       "16": "REDUCE RELATIONS", "160": "Reduce relations, not specified below",
                       "161": "Reduce or break diplomatic relations",
                       "162": "Reduce or stop material aid, not specified below",
                       "1621": "Reduce or stop economic assistance", "1622": "Reduce or stop military assistance",
                       "1623": "Reduce or stop humanitarian assistance", "163": "Impose embargo, boycott, or sanctions",
                       "164": "Halt negotiations", "165": "Halt mediation",
                       "166": "Expel or withdraw, not specified below", "1661": "Expel or withdraw peacekeepers",
                       "1662": "Expel or withdraw inspectors, observers", "1663": "Expel or withdraw aid agencies",
                       "17": "COERCE", "170": "Coerce, not specified below",
                       "171": "Seize or damage property, not specified below", "1711": "Confiscate property",
                       "1712": "Destroy property", "172": "Impose administrative sanctions, not specified below",
                       "1721": "Impose restrictions on political freedoms",
                       "1722": "Ban political parties or politicians", "1723": "Impose curfew",
                       "1724": "Impose state of emergency or martial law",
                       "173": "Arrest, detain, or charge with legal action", "174": "Expel or deport individuals",
                       "175": "Use tactics of violent repression", "176": "Attack cybernetically", "18": "ASSAULT",
                       "180": "Use unconventional violence, not specified below",
                       "181": "Abduct, hijack, or take hostage", "182": "Physically assault, not specified below",
                       "1821": "Sexually assault", "1822": "Torture", "1823": "Kill by physical assault",
                       "183": "Conduct suicide, car, or other non-military bombing, not specified below",
                       "1831": "Carry out suicide bombing", "1832": "Carry out vehicular bombing",
                       "1833": "Carry out roadside bombing", "1834": "Carry out location bombing",
                       "184": "Use as human shield", "185": "Attempt to assassinate", "186": "Assassinate",
                       "19": "FIGHT", "190": "Use conventional military force, not specified below",
                       "191": "Impose blockade, restrict movement", "192": "Occupy territory",
                       "193": "Fight with small arms and light weapons", "194": "Fight with artillery and tanks",
                       "195": "Employ aerial weapons, not specified below",
                       "1951": "Employ precision-guided aerial munitions",
                       "1952": "Employ remotely piloted aerial munitions", "196": "Violate ceasefire",
                       "20": "USE UNCONVENTIONAL MASS VIOLENCE",
                       "200": "Use unconventional mass violence, not specified below",
                       "201": "Engage in mass expulsion", "202": "Engage in mass killings",
                       "203": "Engage in ethnic cleansing",
                       "204": "Use weapons of mass destruction, not specified below",
                       "2041": "Use chemical, biological, or radiological weapons", "2042": "Detonate nuclear weapons",
                       "0812": "Ease ban on political parties or politicians", "0813": "Ease curfew",
                       "0814": "Ease state of emergency or martial law", "082": "Ease political dissent",
                       "083": "Accede to requests or demands for political reform, not specified below",
                       "0831": "Accede to demands for change in leadership",
                       "0832": "Accede to demands for change in policy", "0833": "Accede to demands for rights",
                       "0834": "Accede to demands for change in institutions, regime",
                       "084": "Return, release, not specified below", "0841": "Return, release person(s)",
                       "0842": "Return, release property", "085": "Ease economic sanctions, boycott, embargo",
                       "086": "Allow international involvement, not specified below",
                       "0861": "Receive deployment of peacekeepers", "0862": "Receive inspectors",
                       "0863": "Allow humanitarian access", "087": "De-escalate military engagement",
                       "0871": "Declare truce, ceasefire", "0872": "Ease military blockade",
                       "0873": "Demobilize armed forces", "0874": "Retreat or surrender militarily",
                       "441": "EQ - Earthquake", "442": "TC - Tropical Cyclone", "443": "FL - Flood",
                       "444": "VO - Volcano", "445": "Other natural disasters"}
