---
# logging configurations
version: 1

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  info_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: ./logs/info.log
    maxBytes: 1024 #485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: ./logs/errors.log
    maxBytes: 1024 #485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  App:
    level: DEBUG
    handlers: [console, info_handler, error_handler]
    propagate: no

root:
  level: DEBUG
  handlers: [console, info_handler, error_handler]